name: Update update-notifier

on:
  workflow_dispatch:
  schedule:
    - cron: '25 5 * * 1,4'

jobs:
  composer-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          dependency-versions: highest

      - name: Run Composer Update
        run: |
          composer update --no-interaction --no-progress

      - name: Generate composer diff
        id: composer_diff
        uses: IonBazan/composer-diff-action@v1
        with:
          base: HEAD
          direct: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.UNBLIBBOT_PAT_TOKEN }}
          commit-message: Update Application and Dependencies
          committer: UNB Libraries CodeBot <libsystems@unb.ca>
          author: UNB Libraries CodeBot <libsystems@unb.ca>
          signoff: false
          branch: application-updates
          delete-branch: true
          title: 'Application Updates'
          body: |
            This is an automated PR generated by GitHub Actions to update PHP Composer dependencies.

            ${{ steps.composer_diff.outputs.composer_diff }}
